#include <dbus/dbus.h>

void bluezError(DBusError* err) {
    if (dbus_error_is_set(err)) {
        std::cerr << "D-Bus Error: " << err->message << std::endl;
        dbus_error_free(err);
        exit(EXIT_FAILURE);
    }
}

// Parses the nested "Track" metadata dictionary inside the root property array
void bluezTrack(DBusMessageIter* dict_iter) {
    DBusMessageIter entry_iter;
    dbus_message_iter_recurse(dict_iter, &entry_iter);

    while (dbus_message_iter_get_arg_type(&entry_iter) == DBUS_TYPE_DICT_ENTRY) {
        DBusMessageIter sub_iter;
        dbus_message_iter_recurse(&entry_iter, &sub_iter);

        const char* key;
        dbus_message_iter_get_basic(&sub_iter, &key);
        dbus_message_iter_next(&sub_iter);

        DBusMessageIter variant_iter;
        dbus_message_iter_recurse(&sub_iter, &variant_iter);
        int type = dbus_message_iter_get_arg_type(&variant_iter);

        std::string k(key);
        if (type == DBUS_TYPE_STRING) {
            if ((k == "Album" || k == "Artist" || k == "Title")) {
                const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
                S[k] = val;
            } else if (k == "ImgHandle") { // not work yet
                const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
                coverart = val;
            }
        } else if (k == "Duration" && type == DBUS_TYPE_UINT32) {
            uint32_t val; dbus_message_iter_get_basic(&variant_iter, &val);
            Time = val / 1000; // ms to s
        }
        dbus_message_iter_next(&entry_iter);
    }
}

// Parses the root array response generated by the GetAll method
void bluezAll(DBusMessageIter* array_iter) {
    DBusMessageIter entry_iter;
    dbus_message_iter_recurse(array_iter, &entry_iter);

    // Loop through root array entries { String : Variant }
    while (dbus_message_iter_get_arg_type(&entry_iter) == DBUS_TYPE_DICT_ENTRY) {
        DBusMessageIter sub_iter;
        dbus_message_iter_recurse(&entry_iter, &sub_iter);

        const char* key;
        dbus_message_iter_get_basic(&sub_iter, &key);
        dbus_message_iter_next(&sub_iter);

        DBusMessageIter variant_iter;
        dbus_message_iter_recurse(&sub_iter, &variant_iter);
        int type = dbus_message_iter_get_arg_type(&variant_iter);

        std::string k(key);

        if (k == "Status" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::string Status(val);
                 if (Status == "paused")  state = "pause";
            else if (Status == "playing") state = "play";
            else                          state = "stop";
        } else if (k == "Position" && type == DBUS_TYPE_UINT32) {
            uint32_t val; dbus_message_iter_get_basic(&variant_iter, &val);
            elapsed = val / 1000; // ms to s
        } else if (k == "Track" && type == DBUS_TYPE_ARRAY) { // Album Artist Title Time
            bluezTrack(&variant_iter);
        }
        dbus_message_iter_next(&entry_iter);
    }
    if (elapsed == 0) state = "stop";
}

void bluezMeta() {
    DBusError err;
    dbus_error_init(&err);

    DBusConnection* conn = dbus_bus_get(DBUS_BUS_SYSTEM, &err);
    bluezError(&err);
    
    std::string dest = fileContent("/srv/http/data/shm/bluetoothdest");
    DBusMessage* msg = dbus_message_new_method_call(
        "org.bluez",                       // destination service
        dest.c_str(),                      // path
        "org.freedesktop.DBus.Properties", // interface
        "GetAll"                           // method
    );

    const char* interface_to_query = "org.bluez.MediaPlayer1";
    dbus_message_append_args(msg, DBUS_TYPE_STRING, &interface_to_query, DBUS_TYPE_INVALID);

    DBusMessage* reply = dbus_connection_send_with_reply_and_block(conn, msg, -1, &err);
    dbus_message_unref(msg);
    bluezError(&err);

    DBusMessageIter reply_iter;
    dbus_message_iter_init(reply, &reply_iter);

    // GetAll directly returns an Array of Dict Entries (a{sv})
    if (dbus_message_iter_get_arg_type(&reply_iter) == DBUS_TYPE_ARRAY) {
        bluezAll(&reply_iter);
    } else {
        std::cerr << "Unexpected response format returned from GetAll." << std::endl;
    }

    dbus_message_unref(reply);
    dbus_connection_unref(conn);
}
