// g++ -O2 bluez_meta.cpp -o bluez_meta $( pkg-config --cflags --libs dbus-1 )

#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>
#include <dbus/dbus.h>

void check_error(DBusError* err) {
    if (dbus_error_is_set(err)) {
        std::cerr << "D-Bus Error: " << err->message << std::endl;
        dbus_error_free(err);
        exit(EXIT_FAILURE);
    }
}

// Parses the nested "Track" metadata dictionary inside the root property array
void parse_track_metadata(DBusMessageIter* dict_iter) {
    DBusMessageIter entry_iter;
    dbus_message_iter_recurse(dict_iter, &entry_iter);

    while (dbus_message_iter_get_arg_type(&entry_iter) == DBUS_TYPE_DICT_ENTRY) {
        DBusMessageIter sub_iter;
        dbus_message_iter_recurse(&entry_iter, &sub_iter);

        const char* key;
        dbus_message_iter_get_basic(&sub_iter, &key);
        dbus_message_iter_next(&sub_iter);

        DBusMessageIter variant_iter;
        dbus_message_iter_recurse(&sub_iter, &variant_iter);
        int type = dbus_message_iter_get_arg_type(&variant_iter);

        std::string key_str(key);

        if (key_str == "Title" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "Title: " << val << std::endl;
        } 
        else if (key_str == "Album" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "Album: " << val << std::endl;
        } 
        else if (key_str == "Artist" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "Artist: " << val << std::endl;
        } 
        else if (key_str == "Duration" && type == DBUS_TYPE_UINT32) {
            uint32_t val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "Time: " << (val / 1000) << std::endl; // BlueZ uses milliseconds
        }
        else if (key_str == "ImgHandle" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "Cover Art Image Token: " << val << std::endl;
        }

        dbus_message_iter_next(&entry_iter);
    }
}

// Parses the root array response generated by the GetAll method
void parse_get_all_properties(DBusMessageIter* array_iter) {
    DBusMessageIter entry_iter;
    dbus_message_iter_recurse(array_iter, &entry_iter);

    // Loop through root array entries { String : Variant }
    while (dbus_message_iter_get_arg_type(&entry_iter) == DBUS_TYPE_DICT_ENTRY) {
        DBusMessageIter sub_iter;
        dbus_message_iter_recurse(&entry_iter, &sub_iter);

        const char* key;
        dbus_message_iter_get_basic(&sub_iter, &key);
        dbus_message_iter_next(&sub_iter);

        DBusMessageIter variant_iter;
        dbus_message_iter_recurse(&sub_iter, &variant_iter);
        int type = dbus_message_iter_get_arg_type(&variant_iter);

        std::string key_str(key);

        if (key_str == "Status" && type == DBUS_TYPE_STRING) {
            const char* val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::string state(val);
                 if (state == "paused")  state = "pause";
            else if (state == "playing") state = "play";
            else                         state = "stop";
            std::cout << "state: " << state << std::endl;
        } else if (key_str == "Position" && type == DBUS_TYPE_UINT32) {
            uint32_t val; dbus_message_iter_get_basic(&variant_iter, &val);
            std::cout << "elapsed: " << (val / 1000) << std::endl; // ms to s
        } else if (key_str == "Track" && type == DBUS_TYPE_ARRAY) { // sub-dictionary
            parse_track_metadata(&variant_iter);
        }
        dbus_message_iter_next(&entry_iter);
    }
}

int main() {
    
    DBusError err;
    dbus_error_init(&err);

    DBusConnection* conn = dbus_bus_get(DBUS_BUS_SYSTEM, &err);
    check_error(&err);
    
    std::ifstream file("/srv/http/data/shm/bluetoothdest");
    std::string dest;
    std::getline(file, dest);

    DBusMessage* msg = dbus_message_new_method_call(
        "org.bluez",                       // destination service
        dest.c_str(),                      // path
        "org.freedesktop.DBus.Properties", // interface
        "GetAll"                           // method
    );

    const char* interface_to_query = "org.bluez.MediaPlayer1";
    dbus_message_append_args(msg, DBUS_TYPE_STRING, &interface_to_query, DBUS_TYPE_INVALID);

    DBusMessage* reply = dbus_connection_send_with_reply_and_block(conn, msg, -1, &err);
    dbus_message_unref(msg);
    check_error(&err);

    DBusMessageIter reply_iter;
    dbus_message_iter_init(reply, &reply_iter);

    // GetAll directly returns an Array of Dict Entries (a{sv})
    if (dbus_message_iter_get_arg_type(&reply_iter) == DBUS_TYPE_ARRAY) {
        parse_get_all_properties(&reply_iter);
    } else {
        std::cerr << "Unexpected response format returned from GetAll." << std::endl;
    }

    dbus_message_unref(reply);
    dbus_connection_unref(conn);
    return 0;
}
